[package]
name = "my_art_shivanshu"
version = "0.1.0"
edition = "2021"
authors = ["shivanshu"]
description = "Crate made for learning how to publish crates"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
